## Модуль 04: Python для работы с данными

### Лабораторная работа 4.1

1. В режиме калькулятора посчитать:
    - Сумму чисел от 0 до 10
    - Произведение их на 2
    - Средний возраст в аудитории
2. Описать в виде списка, кортежа и словаря
    - Состав семьи
    - Состав группы
    - Зачетную книжку студента

__Пункт 1__

In [47]:
x = 1+2+3+4+5+6+7+8+9+10
print(f"Сумма чисел от 0 до 10: {x}")

Сумма чисел от 0 до 10: 55


In [48]:
xx = x*2
print(f":Произведение их на 2: {xx}")

:Произведение их на 2: 110


In [49]:
mean_age = (19+18+17+20+21+20+19+19+19)/9
print(f"Средний возраст студентов: {mean_age}")

Средний возраст студентов: 19.11111111111111


__Пункт 2__

In [51]:
# Список
fam_list = ['mom','dad','I']
group_list = ['student1','student3','student2']
book_list = [5,4,5]
print(' Состав семьи', fam_list, '\n',
      'Состав группы', group_list, '\n',
      'Зачетная книжка студента', book_list)

 Состав семьи ['mom', 'dad', 'I'] 
 Состав группы ['student1', 'student3', 'student2'] 
 Зачетная книжка студента [5, 4, 5]


In [53]:
# Кортеж
fam_cor = ('mom','dad','I')
group_cor = ('student1','student3','student2')
book_cor = (5,4,5)
print(' Состав семьи', fam_cor, '\n',
      'Состав группы', group_cor, '\n',
      'Зачетная книжка студента', book_cor)

 Состав семьи ('mom', 'dad', 'I') 
 Состав группы ('student1', 'student3', 'student2') 
 Зачетная книжка студента (5, 4, 5)


In [54]:
# Словарь
fam_slov = {'mom':'Sveta','dad':'Ivan','I':'Mary'}
group_slov = {1:'student1',2:'student3',3:'student2'}
book_slov = {'python':5,'math':4,'sql':5}
print(' Состав семьи', fam_slov, '\n',
      'Состав группы', group_slov, '\n',
      'Зачетная книжка студента', book_slov)

 Состав семьи {'mom': 'Sveta', 'dad': 'Ivan', 'I': 'Mary'} 
 Состав группы {1: 'student1', 2: 'student3', 3: 'student2'} 
 Зачетная книжка студента {'python': 5, 'math': 4, 'sql': 5}


In [55]:
## Исходная программа
A = [3,4,2,1,0,8,9,-1,100,0]
min = A.pop()

while A:
    a = A.pop()
    if a < min:
        min = a

Доработать программу так, чтобы она:
1. печатала содержимое всех переменных на каждой итерации цикла,
2. искала максимальный элемент списка,
3. искала минимальный и максимальный элементы списка,
4. определяла порядковые номера этих элементов.

In [59]:
A = [3,4,2,1,0,8,9,-1,100,0]
B = A.copy()
maxi = A.pop()
mini = B.pop()
print(f"A: {A}")
print(f"B: {B}")
print(f"maxi: {maxi}")
print(f"mini: {mini}")

for i in range(len(A)):
    a = A.pop()
    print(f"A: {A}")
    print(f"a: {a}")
    if a > maxi:
        maxi = a
        print(f"maxi: {maxi}")
        i_max = i
        print(f"i_max: {i_max}")
    b = B.pop()
    print(f"B: {B}")
    print(f"b: {b}")
    if b < mini:
        mini = b
        print(f"mini: {mini}")
        i_min = i
        print(f"i_min: {i_min}")

print("Min:", mini, 'на', i_min, 'месте')
print("Max:", maxi, 'на', i_max, 'месте')

A: [3, 4, 2, 1, 0, 8, 9, -1, 100]
B: [3, 4, 2, 1, 0, 8, 9, -1, 100]
maxi: 0
mini: 0
A: [3, 4, 2, 1, 0, 8, 9, -1]
a: 100
maxi: 100
i_max: 0
B: [3, 4, 2, 1, 0, 8, 9, -1]
b: 100
A: [3, 4, 2, 1, 0, 8, 9]
a: -1
B: [3, 4, 2, 1, 0, 8, 9]
b: -1
mini: -1
i_min: 1
A: [3, 4, 2, 1, 0, 8]
a: 9
B: [3, 4, 2, 1, 0, 8]
b: 9
A: [3, 4, 2, 1, 0]
a: 8
B: [3, 4, 2, 1, 0]
b: 8
A: [3, 4, 2, 1]
a: 0
B: [3, 4, 2, 1]
b: 0
A: [3, 4, 2]
a: 1
B: [3, 4, 2]
b: 1
A: [3, 4]
a: 2
B: [3, 4]
b: 2
A: [3]
a: 4
B: [3]
b: 4
A: []
a: 3
B: []
b: 3
Min: -1 на 1 месте
Max: 100 на 0 месте


In [60]:
## Пример из занятия
s = 'abcdefghijklmnop'
while s != "":
    print(s)
    s = s[1:-1]

abcdefghijklmnop
bcdefghijklmno
cdefghijklmn
defghijklm
efghijkl
fghijk
ghij
hi


In [61]:
## Пример из занятия
for i in range(1,10):
    for j in range(1,10):
        print(" %2i" % (i*j), end = '')
    print()

  1  2  3  4  5  6  7  8  9
  2  4  6  8 10 12 14 16 18
  3  6  9 12 15 18 21 24 27
  4  8 12 16 20 24 28 32 36
  5 10 15 20 25 30 35 40 45
  6 12 18 24 30 36 42 48 54
  7 14 21 28 35 42 49 56 63
  8 16 24 32 40 48 56 64 72
  9 18 27 36 45 54 63 72 81


Выполните эти задачи в программном режиме.
1. Посчитать сумму чисел от 0 до 10
2. Произведение их на 2
3. Вычислить средний возраст в аудитории

Используйте циклы for и while для решения каждой задачи.

__Задача 1__

In [62]:
s = 0
for i in range(0,11):
    s += i
print(f"Сумма чисел от 0 до 10 (for): {s}")

s = 0
i = 0
while i <= 10:
    s += i
    i += 1
print(f"Сумма чисел от 0 до 10 (while): {s}")

Сумма чисел от 0 до 10 (for): 55
Сумма чисел от 0 до 10 (while): 55


__Задача 2__

In [69]:
print("for \n")
s = 0
for i in range(0,11):
    s1 = i*2
    s += s1
    print(f"Элементы умноженные на 2: {s1}")
print(f"!!!!Произведение их на 2: {s}")

print("\n while \n")
s = 0
i = 0
while i <= 10:
    s1 = i*2
    s += s1
    i += 1
    print(f"Элементы умноженные на 2: {s1}")
print(f"!!!!Произведение их на 2: {s}")

for 

Элементы умноженные на 2: 0
Элементы умноженные на 2: 2
Элементы умноженные на 2: 4
Элементы умноженные на 2: 6
Элементы умноженные на 2: 8
Элементы умноженные на 2: 10
Элементы умноженные на 2: 12
Элементы умноженные на 2: 14
Элементы умноженные на 2: 16
Элементы умноженные на 2: 18
Элементы умноженные на 2: 20
!!!!Произведение их на 2: 110

 while 

Элементы умноженные на 2: 0
Элементы умноженные на 2: 2
Элементы умноженные на 2: 4
Элементы умноженные на 2: 6
Элементы умноженные на 2: 8
Элементы умноженные на 2: 10
Элементы умноженные на 2: 12
Элементы умноженные на 2: 14
Элементы умноженные на 2: 16
Элементы умноженные на 2: 18
Элементы умноженные на 2: 20
!!!!Произведение их на 2: 110


__Задача 3__

In [70]:
age = [19,18,17,20,21,20,19,19,19]
s = 0
i = 0
while age:
    a = age.pop()
    i += 1
    s += a
print(f"Средний возраст студентов (while): {s/i}")

age = [19,18,17,20,21,20,19,19,19]
s = 0
i = 0
for p in age:
    i += 1
    s += p
print(f"Средний возраст студентов (for): {s/i}")

Средний возраст студентов (while): 19.11111111111111
Средний возраст студентов (for): 19.11111111111111


### Лабораторная работа 4.2

Выполните эти задачи с помощью numpy:
1. Посчитать сумму чисел от 0 до 10.
2. Произведение их на 2.
3. Вычислить средний возраст в аудитории.

In [71]:
import numpy as np
from numpy.random import randint

__Задача 1__

In [74]:
s = 0
a = np.arange(11)
for i in a:
    s += a[i]
print(f"Сумма чисел от 0 до 10 (1 вариант с циклом): {s}")

print(f"Сумма чисел от 0 до 10 (2 вариант краткий): {sum(np.arange(11))}")

Сумма чисел от 0 до 10 (1 вариант с циклом): 55
Сумма чисел от 0 до 10 (2 вариант краткий): 55


__Задача 2__

In [76]:
s = 0
a = np.arange(11)
for i in a:
    s += a[i]*2

print(f"Произведение их на 2 (1 вариант с циклом): {s}")
print(f"Произведение их на 2 (2 вариант краткий): {sum(np.arange(11))*2}")

Произведение их на 2 (1 вариант с циклом): 110
Произведение их на 2 (2 вариант краткий): 110


__Задача 3__

In [78]:
age = np.random.randint(18,25,10)
age

array([24, 20, 19, 20, 23, 24, 22, 23, 22, 21])

In [79]:
print(f"Средний возраст студентов (for): {np.mean(age)}")

Средний возраст студентов (for): 21.8


### Лабораторная работа 4.3

1) Установить NumPy любым способом. + лог установки сохранить в файл

6) Программу, которая это делает (или jupyter-файл) опубликуйте в гите. Прилодите данный с которыми она работает (csv, txt...)

https://gitflic.ru/project/msq/shift_labs

2) Создать с помощью электронной таблицы матрицу с какими-либо данными (можно использовать готовые данные, но не забывайте об их конфиденциальности!)

3) Загрузите данные из электронной таблицы в матрицу numpy

In [42]:
import numpy as np

In [46]:
data = np.genfromtxt('import_4_3.csv', delimiter=';')

In [47]:
data

array([[1., 2., 4.],
       [1., 3., 3.],
       [1., 2., 4.],
       [1., 3., 5.],
       [1., 3., 4.],
       [1., 4., 3.],
       [1., 3., 5.],
       [1., 4., 3.],
       [1., 4., 2.],
       [1., 5., 4.],
       [1., 4., 5.],
       [1., 5., 2.],
       [1., 5., 4.],
       [1., 6., 2.],
       [1., 5., 4.],
       [1., 6., 5.]])

4) Создайте единичную матрицу размерности, идентичной полученной из электронной таблицы

In [50]:
data.shape

(16, 3)

In [51]:
data_one = np.eye(16,3)
data_one

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

5) Перемножьте одно на другое и экспортируйте результат в электронную таблицу

In [52]:
fin = data*data_one
fin

array([[1., 0., 0.],
       [0., 3., 0.],
       [0., 0., 4.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.savetxt('output_4_3.csv', fin, delimiter=';')